CREATE TABLE panda_app(
id INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
app_name VARCHAR(100) NOT NULL COMMENT '应用名',
app_alias VARCHAR(100) NOT NULL COMMENT '应用别名',
business_line INT(12) NOT NULL COMMENT '业务线',
state TINYINT(1) NOT NULL DEFAULT '0',
update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='应用'